### PR TITLE
Lab1 : Threads

### PR DESCRIPTION
**Pull request by UsusCimex**

### CODE REVIEW

**Comment by k-stolyarov** [comment]
are you kidding ?!  I've already asked to create pull request with all changes. I do not want to explore repository and looks for correct implementation through all  commits and branches.. Please pay respect to my free time.

**Comment by UsusCimex** [comment]
> are you kidding ?! I've already asked to create pull request with all changes. I do not want to explore repository and looks for correct implementation through all commits and branches.. Please pay respect to my free time.

SORRY! I couldn't restore all the commits properly... Can you check the whole file?...

**Comment by k-stolyarov** [comment]
Change branch commits . I want to be able to write comments to all changes.

**Comment by UsusCimex** [comment]
git is kidding me... Can I leave everything as it is?

**Comment by k-stolyarov** [comment]
nope,  if you want me to review  this task  please create correct pull request.

**Pull request closed without merging**
